[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "https://wanrenbuffet.online/api/:splat"
  status = 200
  force = true


  [[redirects]]
  from = "/Table/*"
  to = "https://wanrenbuffet.online/Table/:splat"
  status = 200
  force = true
